markdown: kramdown
pygments: true
permalink: /:year/:month/:title/
url: http://verraes.net
description: "I'm Mathias Verraes. I build enterprise web applications, and I deal with complex legacy systems. This is my blog."